# Generated by Django 4.2 on 2026-07-17 08:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube ou Vimeo')),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('in_progress', 'En cours'), ('planned', 'Planifié')], default='completed', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(to='core.techstack')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/extra/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='projects.project')),
            ],
        ),
    ]
